ci: add failure case for tagged action test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -146,12 +146,25 @@ jobs:
     steps:
       - name: ROT-13
         uses: nikoheikkila/rot-13-action@v1
-        id: rot13
+        id: valid
         with:
           string: ${{ env.original }}
 
       - name: Fail expectation
-        if: steps.rot13.outputs.result != env.transformed
+        if: steps.valid.outputs.result != env.transformed
         run: |
-          echo "::error::Expected result of transformation was '${{ env.transformed }}', but got '${{ steps.rot13.outputs.result }}'"
+          echo "::error::Expected result of transformation was '${{ env.transformed }}', but got '${{ steps.valid.outputs.result }}'"
+          exit 1
+
+      - name: Test with empty input
+        uses: nikoheikkila/rot-13-action@v1
+        id: invalid
+        continue-on-error: true
+        with:
+          string: ""
+
+      - name: Fail if empty input succeeds
+        if: steps.invalid.outcome != 'failure'
+        run: |
+          echo "::error::Expected action to fail when given empty input, but it succeeded."
           exit 1
