feat: rewrite into a ROT-13 example action

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,6 +8,10 @@ on:
     branches:
       - main
 
+env:
+  original: "Hello, World!"
+  transformed: "Uryyb, Jbeyq!"
+
 jobs:
   test-unit:
     name: Unit Tests
@@ -51,14 +55,17 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v5
 
-      - name: Greet user
+      - name: ROT-13
         uses: ./
-        id: hello
+        id: rot13
         with:
-          who-to-greet: ${{ github.actor }}
+          string: ${{ env.original }}
 
-      - name: Get the output time
-        run: echo "The time was ${{ steps.hello.outputs.time }}"
+      - name: Fail expectation
+        if: steps.rot13.outputs.result != env.transformed
+        run: |
+          echo "::error::Expected result of transformation was '${{ env.transformed }}', but got '${{ steps.rot13.outputs.result }}'"
+          exit 1
 
   release:
     name: Release
@@ -110,18 +117,3 @@ jobs:
           gh release create "${{ steps.tag_version.outputs.new_version }}" \
             --title "Release ${{ steps.tag_version.outputs.new_version }}" \
             --generate-notes
-
-  test-action:
-    name: Test tagged action
-    runs-on: ubuntu-latest
-    needs: [release]
-
-    steps:
-      - name: Greet user
-        uses: nikoheikkila/hello-world-javascript-action@v1
-        id: hello
-        with:
-          who-to-greet: ${{ github.actor }}
-
-      - name: Get the output time
-        run: echo "The time was ${{ steps.hello.outputs.time }}"
